
//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace DotNetCampus.Terminal.Views
{
    public partial class RootView : Toplevel
    {
        private void InitializeComponent()
        {
            Width = Dim.Fill(0);
            Height = Dim.Fill(0);
            X = 0;
            Y = 0;
            Visible = true;
            Arrangement = ViewArrangement.Overlapped;
            CanFocus = true;
            ShadowStyle = ShadowStyle.None;
            Modal = false;
            TextAlignment = Alignment.Start;
            Title = "DotNetCampus Terminal";
        }
    }
}
